version: '2'
services:
    bot:
        image: sad0vnikov/marvin-bot:v0.1.0
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - marvin-db
        links:
            - marvin-db
        env_file: config.env
        networks:
          - marvin
          - marvin-mongo

    marvin-db:
        image: mongo
        restart: unless-stopped
        volumes:
          - ./db:/data/db
        ports:
          - "27017:27017"
        networks:
          - marvin-mongo
networks:
  marvin:
    driver: bridge
  marvin-mongo:
    driver: bridge
